"""
Django settings for VIM project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# web-app/django:/virtual-instrument-museum/vim-app
BASE_DIR = Path(__file__).resolve().parent.parent
# /virtual-instrument-museum/
ROOT_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

IS_DEVELOPMENT = bool(os.environ.get("MODE") == "dev")
IS_PRODUCTION = bool(os.environ.get("MODE") == "prod")
IS_TEST = bool(os.environ.get("MODE") == "test")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_DEVELOPMENT

ALLOWED_HOSTS = [os.environ.get("HOST_NAME")]

if DEBUG:
    import socket

    INTERNAL_IPS = [
        socket.gethostbyname("vim-nginx"),
    ]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "VIM.apps.main",
    "VIM.apps.instruments",
    "django_vite",
    "django_cleanup.apps.CleanupConfig",  # Must be last - handles orphaned file cleanup
]

if IS_DEVELOPMENT:
    INSTALLED_APPS += ["django_extensions", "debug_toolbar"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if IS_DEVELOPMENT:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "VIM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "VIM" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "VIM.wsgi.application"

# Database configuration
# Check if running in test mode
if IS_TEST:
    # Use test database (isolated from development)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("TEST_POSTGRES_DB", "vim_test_db"),
            "USER": os.environ.get("TEST_POSTGRES_USER", "test_user"),
            "PASSWORD": os.environ.get("TEST_POSTGRES_PASSWORD", "test_password"),
            "HOST": "postgres-test",
            "PORT": "5432",
        }
    }
else:
    # Use development or production database
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": "vim-db",
            "PORT": "5432",
        }
    }

# Cache configuration
# django-ratelimit uses Django's cache framework to track request rates
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "ratelimit-cache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = "/virtual-instrument-museum/static/"
STATIC_URL = "static/"

if not IS_DEVELOPMENT:
    STATICFILES_DIRS = [
        ROOT_DIR / "frontend" / "dist",
    ]

DJANGO_VITE = {
    "default": {
        "dev_mode": IS_DEVELOPMENT,
        "dev_server_port": 5173,
        "dev_server_host": "localhost",
        "manifest_path": ROOT_DIR / "frontend" / "dist" / "manifest.json",
    }
}

# Media files (user uploads)
MEDIA_ROOT = ROOT_DIR / "media"
MEDIA_URL = "/media/"
ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/gif", "image/webp"]
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration with environment variables and development fallback
# If EMAIL_HOST is not set, emails will be printed to console (useful for development)
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", "UMIL <noreply@umil.linkedmusic.com>"
)

SITE_NAME = "UMIL"

# TOKEN EXPIRY SETTINGS
# Timeout for password reset and email verification tokens (24 hours)
# Used by default_token_generator for both password reset and email verification links
PASSWORD_RESET_TIMEOUT = 86400  # seconds

# RATE LIMITING SETTINGS
RESEND_EMAIL_COOLDOWN = 60  # seconds
# Session expiry for pending verification email (15 minutes)
PENDING_EMAIL_SESSION_EXPIRY = 900

# django-ratelimit settings
# Rate limit for instrument creation: 10 instruments per hour per user
RATELIMIT_ENABLE = True  # Can disable rate limiting in tests
RATELIMIT_USE_CACHE = "default"  # Use default cache backend
RATELIMIT_VIEW = (
    "VIM.apps.instruments.utils.response_helpers.handle_rate_limit_exceeded"
)

# Instrument creation rate limits
CREATE_INSTRUMENT_RATE = "10/h"  # 10 instruments per hour per authenticated user (TBD)

# MESSAGE TAGS - Map Django message levels to Bootstrap alert classes
MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# DEPLOYMENT SETTINGS

CSRF_COOKIE_SECURE = IS_PRODUCTION
CSRF_TRUSTED_ORIGINS = [f'https://{os.environ.get("HOST_NAME")}']
SESSION_COOKIE_SECURE = IS_PRODUCTION

# SOLR SETTINGS

SOLR_URL = "http://solr:8983/solr/virtual-instrument-museum"
SOLR_TIMEOUT = 10
EMPTY_HBS_CATEGORY = "0"

# DEFAULT PAGE SETTINGS
DEFAULT_LANGUAGE = "English"
DEFAULT_PAGE_SIZE = 20

# DDMAL USER ACCOUNT FOR UMIL
DDMAL_USERNAME = "ddmal"
