apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-umil-staging
  namespace: postgres
spec:
  serviceName: postgres-umil-staging
  replicas: 1
  selector:
    matchLabels:
      app: postgres-umil-staging
  template:
    metadata:
      labels:
        app: postgres-umil-staging
    spec:
      tolerations:
        - effect: NoSchedule
          key: workload
          operator: Equal
          value: database
      nodeSelector:
        workload: database
      containers:
        - name: postgres
          image: postgres:15.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: virtual_instrument_museum_staging
            - name: POSTGRES_USER
              value: vim_admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-umil-staging-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-umil-staging-pvc
