# Uses Compose Specification (https://github.com/compose-spec/compose-spec/blob/master/spec.md)
#
# Note for vim-app volumes: Mounting `/virtual-instrument-museum/frontend/node_modules`
# is needed to (1) expose frontend build tools such as `vite` so `npm run dev` could run,
# and to (2) prevent local `npm install` commands from causing conflicts with the container's dependencies.

services:
  app:
    build:
      context: .
      dockerfile: ./web-app/Dockerfile
      target: dev
    container_name: vim-app
    ports:
      - "5173:5173"
    volumes:
      - ./web-app/django:/virtual-instrument-museum/vim-app
      - ./web-app/frontend/:/virtual-instrument-museum/frontend
      - /virtual-instrument-museum/frontend/node_modules
      - vim-static:/virtual-instrument-museum/static
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MODE=dev
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOST_NAME=${HOST_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  postgres:
    image: postgres:15.4
    container_name: vim-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: vim-nginx
    restart: unless-stopped
    environment:
      - HOST_NAME=${HOST_NAME}
    ports:
      - "8000:80"
    volumes:
      - ./web-app/frontend/assets/:/virtual-instrument-museum/frontend/assets/
      - vim-static:/virtual-instrument-museum/static
    depends_on:
      - app

  solr:
    build: ./solr
    container_name: vim-solr
    restart: unless-stopped
    ports:
      - "8983:8983"

networks:
  vim-net:

volumes:
  vim-static:
