# Generated by Django 4.2.5 on 2025-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_instrumentname_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentname',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
