# Generated by Django 4.2.5 on 2025-08-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("instruments", "0007_instrumentname_is_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instrumentname",
            old_name="status",
            new_name="verification_status",
        ),
        migrations.RemoveField(
            model_name="instrumentname",
            name="is_alias",
        ),
        migrations.RemoveField(
            model_name="instrumentname",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="instrumentname",
            name="umil_label",
            field=models.BooleanField(
                default=False,
                help_text="Is this the label for the instrument? If true, it will be used as the main name.",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentname",
            name="contributor",
            field=models.ForeignKey(
                help_text="User who contributed this name",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="instrumentname",
            constraint=models.UniqueConstraint(
                condition=models.Q(("umil_label", True)),
                fields=("instrument", "language"),
                name="unique_umil_label_per_instrument_language",
            ),
        ),
    ]
