# Generated by Django 4.2.5 on 2025-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "instruments",
            "0008_rename_status_instrumentname_verification_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentname",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("unverified", "Unverified"),
                    ("under_review", "Under Review"),
                    ("needs_additional_review", "Needs Additional Review"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                help_text="Status of the name entry",
                max_length=50,
            ),
        ),
    ]
