# Generated by Django 4.2.5 on 2025-07-25 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0008_remove_instrumentname_is_alias_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instrumentname",
            old_name="status",
            new_name="verification_status",
        ),
        migrations.RemoveField(
            model_name="instrumentname",
            name="is_approved",
        ),
    ]
