# Generated by Django 4.2.5 on 2025-08-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "instruments",
            "0008_rename_status_instrumentname_verification_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentname",
            name="contributor",
            field=models.ForeignKey(
                help_text="User who contributed this name",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
