# Generated by Django 4.2.5 on 2025-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0009_alter_instrumentname_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentname",
            name="deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft delete flag. If true, this name is considered deleted but retained in the database.",
            ),
        ),
    ]
