# Generated by Django 4.2.5 on 2025-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0010_alter_instrumentname_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="html_direction",
            field=models.CharField(
                choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                default="ltr",
                help_text="HTML text direction",
                max_length=3,
            ),
        ),
    ]
