# Generated by Django 4.2.5 on 2025-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0010_instrumentname_deleted"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="instrumentname",
            name="unique_umil_label_per_instrument_language",
        ),
        migrations.AddConstraint(
            model_name="instrumentname",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("umil_label", True), _negated=True),
                    models.Q(("verification_status", "verified"), ("deleted", False)),
                    _connector="OR",
                ),
                name="umil_label=true only if name is Verified and not Deleted",
            ),
        ),
    ]
