# Generated by Django 4.2.5 on 2025-12-04 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("instruments", "0011_language_html_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Who or what called the instrument this?",
                        max_length=50,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Should this source be visible?"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="instrumentname",
            name="contributor",
        ),
        migrations.RemoveField(
            model_name="instrumentname",
            name="source_name",
        ),
        migrations.CreateModel(
            name="InstrumentNameSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Users who contributed this source to this name",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrument_name_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="instruments.instrumentname",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instruments.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instrumentname",
            name="sources",
            field=models.ManyToManyField(
                related_name="instrument_names",
                through="instruments.InstrumentNameSource",
                to="instruments.source",
            ),
        ),
    ]
