# Generated by Django 4.2.5 on 2025-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("instruments", "0012_language_direction"),
        ("instruments", "0013_rename_direction_language_html_direction"),
        ("instruments", "0014_alter_language_html_direction"),
    ]

    dependencies = [
        ("instruments", "0011_auto_20251201_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="html_direction",
            field=models.CharField(
                choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                default="ltr",
                help_text="HTML text direction",
                max_length=3,
            ),
        ),
    ]
