# Generated by Django 4.2.5 on 2026-01-29 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("instruments", "0011_language_html_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="HornbostelSachs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hbs_class",
                    models.CharField(
                        help_text="Hornbostel-Sachs classification",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the main HBS classification for this instrument?",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("under_review", "Under Review"),
                            ("needs_additional_review", "Needs Additional Review"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=50,
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hbs_entries",
                        to="instruments.instrument",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="instrument",
            name="hornbostel_sachs_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently selected Hornbostel–Sachs classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_for",
                to="instruments.hornbostelsachs",
            ),
        ),
    ]
