# Generated by Django 4.2.5 on 2025-12-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0011_language_html_direction"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="avresource",
            constraint=models.UniqueConstraint(
                fields=("instrument", "url"),
                name="unique_avresource_url_per_instrument",
            ),
        ),
    ]
