# Generated by Django 4.2.5 on 2025-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0011_language_html_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentname",
            name="source_name",
            field=models.CharField(
                help_text="Who or what called the instrument this?", max_length=255
            ),
        ),
    ]
