# Generated by Django 4.2.5 on 2026-02-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0012_create_instrument_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avresource",
            name="format",
            field=models.CharField(
                choices=[
                    ("jpg", "JPEG"),
                    ("jpeg", "JPEG (alternative extension)"),
                    ("png", "PNG"),
                    ("gif", "GIF"),
                    ("webp", "WebP"),
                    ("svg", "SVG (Scalable Vector Graphics)"),
                ],
                help_text="Image file format extension",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="avresource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("url__gt", "")),
                fields=("instrument", "url"),
                name="unique_instrument_url",
            ),
        ),
    ]
