# Generated by Django 4.2.5 on 2026-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0013_alter_avresource_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Source/reference for this instrument entry",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="instrumentname",
            name="source_name",
            field=models.CharField(
                help_text="Who or what called the instrument this?", max_length=255
            ),
        ),
    ]
