apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vim-media
  namespace: umil
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
