apiVersion: v1
kind: Secret
metadata:
  name: umil-secret
  namespace: umil
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "k(#n*q9!k)1*c@0#n9vj1kz2op!6&btreze8ent&s=in_*a#%n"
  POSTGRES_PASSWORD: "zH57w2KFGwPIzh0O"
  EMAIL_HOST_PASSWORD: "BAzF4BtHhFE5hNxz1pBbqM/b+aZxNL++1sV9NATJWycD"
