apiVersion: v1
kind: Secret
metadata:
  name: umil-secret
  namespace: umil
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "REDACTED_SECRET_KEY"
  POSTGRES_PASSWORD: "REDACTED_DB_PASSWORD"
  EMAIL_HOST_PASSWORD: "REDACTED_EMAIL_PASSWORD"
