FROM nginx:1.25.2
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./vim.conf.template /etc/nginx/templates/vim.conf.template
COPY ./vim.simssa.ca.crt /etc/nginx/templates/vim.simssa.ca.crt
COPY ./vim.simssa.ca.key /etc/nginx/templates/vim.simssa.ca.key