name: Deploy to Production Server
on: workflow_dispatch

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v5
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Stop the current Docker containers running
        run: |
          ssh -J ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST1 }},${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST_PROD }} ${{ secrets.USERNAME }}@${{ secrets.HOST_PROD }} \
            "cd /virtual_instrument_museum &&
             sudo docker compose stop"
      - name: Fetch new updates from remote `origin` and log current branches
        run: |
          ssh -J ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST1 }},${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST_PROD }} ${{ secrets.USERNAME }}@${{ secrets.HOST_PROD }} \
            "cd /virtual_instrument_museum &&
             sudo git fetch origin -v &&
             sudo git branch -v"
      - name: Checkout to `main` branch and pull new changes 
        run: |
          ssh -J ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST1 }},${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST_PROD }} ${{ secrets.USERNAME }}@${{ secrets.HOST_PROD }} \
            "cd /virtual_instrument_museum &&
             sudo git checkout main &&
             sudo git pull origin main"
      - name: Build docker images
        run: |
          ssh -J ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST1 }},${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST_PROD }} ${{ secrets.USERNAME }}@${{ secrets.HOST_PROD }} \
            "cd /virtual_instrument_museum &&
             sudo docker compose build --no-cache"
      - name: Start the services
        run: |
          ssh -J ${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST1 }},${{ secrets.PROXY_USERNAME }}@${{ secrets.PROXY_HOST_PROD }} ${{ secrets.USERNAME }}@${{ secrets.HOST_PROD }} \
            "cd /virtual_instrument_museum &&
             sudo docker compose up -d"
