name: CI - Test Docker build for deployment

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  ci-build-deployment:
    runs-on: ubuntu-latest
    env:
      HOST_NAME: umil.linkedmusic.ca
      DJANGO_SECRET_KEY: ${{ secrets.CI_DJANGO_SECRET_KEY }}
      POSTGRES_DB: virtual_instrument_museum
      POSTGRES_USER: ${{ secrets.CI_POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}

    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Build UMIL with Production compose file
        run: |
          docker compose -f docker-compose-deployment.yml build

      - name: List built Docker images
        run: |
          docker images
