name: frontend-format
on: [push, pull_request]
jobs:
  format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Run djlint via Poetry
        run: |
          cd web-app/django/VIM/templates/
          poetry run djlint . --check --extension html --exclude "migrations/*"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "web-app/frontend/package-lock.json"

      - name: Install frontend dependencies
        run: |
          cd web-app/frontend
          npm ci

      - name: Run Prettier
        run: npx prettier --check "**/*.scss" "**/*.js" "**/*.ts"
