name: frontend-format
on: [push, pull_request]
jobs:
  format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Run Prettier
        run: npx prettier --check "**/*.css" "**/*.js" --trailing-comma es5

      - name: Run djlint via Poetry
        run: poetry run djlint . --check --extension html --exclude "migrations/*"
